[package]
name = "iptmnet_data_importer"
version = "0.1.0"
authors = ["Sachin <sachinx0e@gmail.com>"]

[dependencies]
postgres = "0.15"
log = "0.4"
simplelog = "^0.5.0"
csv = "1.0.0-beta.5"
serde = "1.0.33"
serde_derive = "1.0.33"
pbr = "1.0.0"
clap = "~2.31"